<?php

namespace DoctrineORMModule\Proxy\__CG__\Common\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Atendimentos extends \Common\Entity\Atendimentos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'idAtendimentos', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'protocoloAtendimento', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'nmrContato', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'dataAtendimento', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'idStatusAtendimentos', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'idUsuarioAtendimento');
        }

        return array('__isInitialized__', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'idAtendimentos', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'protocoloAtendimento', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'nmrContato', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'dataAtendimento', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'idStatusAtendimentos', '' . "\0" . 'Common\\Entity\\Atendimentos' . "\0" . 'idUsuarioAtendimento');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Atendimentos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdAtendimentos()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAtendimentos();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAtendimentos', array());

        return parent::getIdAtendimentos();
    }

    /**
     * {@inheritDoc}
     */
    public function setProtocoloAtendimento($protocoloAtendimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtocoloAtendimento', array($protocoloAtendimento));

        return parent::setProtocoloAtendimento($protocoloAtendimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocoloAtendimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocoloAtendimento', array());

        return parent::getProtocoloAtendimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNmrContato($nmrContato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNmrContato', array($nmrContato));

        return parent::setNmrContato($nmrContato);
    }

    /**
     * {@inheritDoc}
     */
    public function getNmrContato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNmrContato', array());

        return parent::getNmrContato();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAtendimento($dataAtendimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAtendimento', array($dataAtendimento));

        return parent::setDataAtendimento($dataAtendimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAtendimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAtendimento', array());

        return parent::getDataAtendimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdStatusAtendimentos(\Common\Entity\StatusAtendimentos $idStatusAtendimentos = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdStatusAtendimentos', array($idStatusAtendimentos));

        return parent::setIdStatusAtendimentos($idStatusAtendimentos);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdStatusAtendimentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdStatusAtendimentos', array());

        return parent::getIdStatusAtendimentos();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuarioAtendimento(\Common\Entity\Usuarios $idUsuarioAtendimento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuarioAtendimento', array($idUsuarioAtendimento));

        return parent::setIdUsuarioAtendimento($idUsuarioAtendimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuarioAtendimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuarioAtendimento', array());

        return parent::getIdUsuarioAtendimento();
    }

}
