<?php

namespace DoctrineORMModule\Proxy\__CG__\Common\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \Common\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'idUsuarios', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'nomeUsuario', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'senhaUsuario', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'nmWhatsapp', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'senhaWhatsap', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'dataCriacao', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'idStatusUsuarios');
        }

        return array('__isInitialized__', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'idUsuarios', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'nomeUsuario', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'senhaUsuario', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'nmWhatsapp', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'senhaWhatsap', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'dataCriacao', '' . "\0" . 'Common\\Entity\\Usuarios' . "\0" . 'idStatusUsuarios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUsuarios()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUsuarios();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuarios', array());

        return parent::getIdUsuarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeUsuario($nomeUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeUsuario', array($nomeUsuario));

        return parent::setNomeUsuario($nomeUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeUsuario', array());

        return parent::getNomeUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenhaUsuario($senhaUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenhaUsuario', array($senhaUsuario));

        return parent::setSenhaUsuario($senhaUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenhaUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenhaUsuario', array());

        return parent::getSenhaUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNmWhatsapp($nmWhatsapp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNmWhatsapp', array($nmWhatsapp));

        return parent::setNmWhatsapp($nmWhatsapp);
    }

    /**
     * {@inheritDoc}
     */
    public function getNmWhatsapp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNmWhatsapp', array());

        return parent::getNmWhatsapp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenhaWhatsap($senhaWhatsap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenhaWhatsap', array($senhaWhatsap));

        return parent::setSenhaWhatsap($senhaWhatsap);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenhaWhatsap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenhaWhatsap', array());

        return parent::getSenhaWhatsap();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCriacao($dataCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCriacao', array($dataCriacao));

        return parent::setDataCriacao($dataCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdStatusUsuarios(\Common\Entity\StatusUsuarios $idStatusUsuarios = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdStatusUsuarios', array($idStatusUsuarios));

        return parent::setIdStatusUsuarios($idStatusUsuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdStatusUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdStatusUsuarios', array());

        return parent::getIdStatusUsuarios();
    }

}
