<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('PV '. $this->translate('Atendimento Página Viva'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/zeroclipboard/ZeroClipboard.js')
        ; ?>
        
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img style="width:35px; height: 35px;"src="<?php echo $this->basePath('img/pagina_viva.jpg') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Atendimento Pagina Viva') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                         <?php if($this->identity()):?>
                            <li><a href="<?php echo $this->url('crm',array('action'=>'get-messages')) ?>"><?php echo $this->translate('Ler Mensagens') ?></a></li>
    						<li><a href="<?php echo $this->url('crm',array('action'=>'register-number')) ?>"><?php echo $this->translate('Registrar número') ?></a></li>
    						<li><a href="<?php echo $this->url('crm',array('action'=>'logout')) ?>"><?php echo $this->translate('Logout') ?></a></li>
						<?php endif;?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container"  style="margin-top: 20px;">
        
        
        	
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
