<?php if(!empty($calls)):?>
    <?php foreach ($calls as $values):?>
        <a href="javascript:void(0);" class="list-group-item" onclick="showMessages(<?php echo $values->getIdAtendimentos()?>,<?php echo $values->getNmrContato();?>)">
            <div class="row">
              	<div class="col-md-3">
              		<img src="<?php echo $this->basePath('img/lorem-ipsum.jpg'); ?>" class="img-responsive img-circle">
              	</div>
              	<div class="col-md-7">
              		<p style="cursor: pointer;"><?echo is_string($values->getNomeContato())?$values->getNomeContato()." - ".$values->getNmrContato():$values->getNmrContato(); ?></p>
              	</div>
              	<div class="col-md-1">
              		<span class="badge"><?php echo $this->countMessagesUnread($this->identity())->getCountMessage($values->getIdAtendimentos());?></span>
              	</div>
            </div>
        </a>
    <?php endforeach;?>
<?php endif;?>