<?php if(!empty($calls)):?>
    <?php foreach ($calls as $values):?>
    <a href="javascript:void(0);" class="list-group-item" onclick="showMessages(<?php echo $values->getIdAtendimentos()?>)">
        <div class="row">
          	<div class="col-md-4">
          		<img src="<?php echo $this->basePath('img/lorem-ipsum.jpg'); ?>" class="img-responsive img-circle">
          	</div>
          	<div class="col-md-8">
          		<label><?php echo $values->getNmrContato(); ?></label>
          	</div>
        </div>
    </a>
    <?php endforeach;?>
<?php endif;?>