<div class="panel panel-default">
      <div class="panel-heading">
      		<?php echo $this->translate("Mensagens")?>      		
      </div>
      <div class="panel-body" style="overflow-y: scroll;height: 400px;">
      <?php $clipboardMessage = null;?>
      <?php foreach($messages as $values):?>
      		
      		<?php if($values->getNmrEnviado() != $this->identity()->getNmWhatsapp()):?>
      			<?php $clipboardMessage.= (is_string($values->getNomeContato())?$values->getNomeContato()." - ":"").$values->getNmrEnviado().": ".$values->getMensagem()." \n"; ?>
      		     <?php $number = $values->getNmrEnviado();?>
                <div class="row" style="margin-bottom:10px">
                	<div class="col-lg-12 col-md-12">
                    	<div class="col-lg-2 col-md-2">
                    		<img src="<?php echo $this->basePath('img/lorem-ipsum.jpg'); ?>" class="img-responsive img-circle">
                    	</div>
                    	<div class="col-lg-8 col-md-8">
                    		<?php if($values->getImagem() > 0):?>
                    			<img src="<?php echo $values->getMensagem();?>" class="img-responsive" style="margin-top:15px;">
                    		<?php else:?>
                    			<p style="margin-top:15px;"><?php echo $values->getMensagem();?></p>
                    		<?php endif;?>
                    	</div>
                    	<div class="col-lg-2 col-md-2">
                    			<div style="margin-top:15px;">
                    				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('H:i');?></small></br>
                    				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('d/m/y');?></small>
                    			</div>
                    	</div>
                	</div>
                </div>
            <?php else:?>
            	<?php $clipboardMessage.= "Atendimento - ".$values->getNmrEnviado().": ".$values->getMensagem()." \n"; ?>
                <div class="row" style="margin-bottom:10px">
                	<div class="col-lg-12 col-md-12">
                		<div class="col-lg-2 col-md-2">
                    		<div style="margin-top:15px;">
                    				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('H:i');?></small></br>
                    				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('d/m/y');?></small>
                			</div>
            			</div>
                    	<div class="col-lg-2 col-md-2 pull-right">
                    		<img src="<?php echo $this->basePath('img/user-placeholder.png'); ?>" class="img-responsive img-circle">
                    	</div>
                    	<div class="col-lg-8 col-md-8">
                    		<p class="pull-right" style="margin-top:15px;"><?php echo $values->getMensagem();?></p>
                    	</div>
                	</div>
                </div>
            <?php endif;?>
        <?php endforeach;?>	
        <div id="new-messages"></div>
        <div class="text-center">
        	<button class="btn btn-xs btn-primary" id="copy-button" data-clipboard-text="<?php echo $clipboardMessage;?>">Copiar Mensagens</button>
        </div>
      </div>
      <div class="panel-footer">
      	<form id="form-<?php echo $number; ?>">
      		<input type="hidden" name="to" value="<?php echo $number; ?>" >
          	 <div class="input-group">
                  <input type="text" class="form-control" name="message" placeholder="Enviar mensagem...">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="button" onclick="sendMessage($('#form-<?php echo $number; ?>'),$(this));">Enviar</button>
                  </span>
              </div><!-- /input-group -->
          </form>
      </div>
    </div>
<script>
//main.js
var client = new ZeroClipboard( document.getElementById("copy-button") );
client.on( "ready", function( readyEvent ) {
      // alert( "ZeroClipboard SWF is ready!" );
    
      client.on( "aftercopy", function( event ) {
        // `this` === `client`
        // `event.target` === the element that was clicked
        //event.target.style.display = "none";
        //alert("Copied text to clipboard: " + event.data["text/plain"] );
      } );
    } );

$('.panel-body').animate({scrollTop: 9999999}, 500);
</script>