<div class="panel panel-default">
      <div class="panel-heading"><?php echo $this->translate("Mensagens")?></div>
      <div class="panel-body" style="overflow-y: scroll;height: 400px;">
      <?php foreach($messages as $values):?>
      		<?php if($values->getNmrEnviado() != $this->identity()->getNmWhatsapp()):?>
      		     <?php $number = $values->getNmrEnviado();?>
                <div class="row" style="margin-bottom:10px">
                	<div class="col-lg-12 col-md-12">
                    	<div class="col-lg-2 col-md-2">
                    		<img src="<?php echo $this->basePath('img/lorem-ipsum.jpg'); ?>" class="img-responsive img-circle">
                    	</div>
                    	<div class="col-lg-10 col-md-10">
                    		<p style="margin-top:15px;"><?php echo $values->getMensagem();?></p>
                    	</div>
                	</div>
                </div>
            <?php else:?>
                <div class="row" style="margin-bottom:10px">
                	<div class="col-lg-12 col-md-12">
                    	<div class="col-lg-2 col-md-2 pull-right">
                    		<img src="<?php echo $this->basePath('img/lorem-ipsum.jpg'); ?>" class="img-responsive img-circle">
                    	</div>
                    	<div class="col-lg-10 col-md-10">
                    		<p class="pull-right" style="margin-top:15px;"><?php echo $values->getMensagem();?></p>
                    	</div>
                	</div>
                </div>
            <?php endif;?>
        <?php endforeach;?>	
      </div>
      <div class="panel-footer">
      	<form id="form-<?php echo $number; ?>">
      		<input type="hidden" name="to" value="<?php echo $number; ?>" >
          	 <div class="input-group">
                  <input type="text" class="form-control" name="message" placeholder="Enviar mensagem...">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="button" onclick="sendMessage($('#form-<?php echo $number; ?>'));">Enviar</button>
                  </span>
              </div><!-- /input-group -->
          </form>
      </div>
    </div>
<script>
$('.panel-body').animate({scrollTop: 9999999}, 500);
</script>