<?php $clipboardMessage = null;?>
      <?php foreach($messages as $values):?>
      		<?php if($values->getNmrEnviado() != $this->identity()->getNmWhatsapp()):?>
      			<?php $clipboardMessage.= (is_string($values->getNomeContato())?$values->getNomeContato()." - ":"").$values->getNmrEnviado().": ".$values->getMensagem()." \n"; ?>
      		     <?php $number = $values->getNmrEnviado();?>
                <div class="row" style="margin-bottom:10px">
                	<div class="col-lg-12 col-md-12">
                    	<div class="col-lg-2 col-md-2">
                    		<img src="<?php echo $this->basePath('img/lorem-ipsum.jpg'); ?>" class="img-responsive img-circle">
                    	</div>
                    	<div class="col-lg-8 col-md-8">
                    		<?php if($values->getImagem() > 0):?>
                    			<img src="<?php echo $values->getMensagem();?>" class="img-responsive" style="margin-top:15px;">
                    		<?php else:?>
                    			<p style="margin-top:15px;"><?php echo $values->getMensagem();?></p>
                    		<?php endif;?>
                    	</div>
                    	<div class="col-lg-2 col-md-2">
                    		<div style="margin-top:15px;">
                				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('H:i');?></small></br>
                				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('d/m/y');?></small>
                			</div>
            			</div>
                	</div>
                </div>
            <?php else:?>
            	<?php $clipboardMessage.= "Atendimento - ".$values->getNmrEnviado().": ".$values->getMensagem()." \n"; ?>
                <div class="row" style="margin-bottom:10px">
                	
                	<div class="col-lg-12 col-md-12">
                		<div class="col-lg-2 col-md-2">
                    		<div style="margin-top:15px;">
                				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('H:i');?></small></br>
                				<small class="data-messages"><?php echo $values->getDataConversaAtendimento()->format('d/m/y');?></small>
                			</div>
            			</div>
                    	<div class="col-lg-2 col-md-2 pull-right">
                    		<img src="<?php echo $this->basePath('img/pagina_viva.jpg'); ?>" class="img-responsive img-circle">
                    	</div>
                    	<div class="col-lg-8 col-md-8">
                    		<p class="pull-right" style="margin-top:15px;"><?php echo $values->getMensagem();?></p>
                    	</div>
                	</div>
                </div>
    	<?php endif;?>
<?php endforeach;?>
<div id="clipboard-new-talk" data-new-talk="<?php echo $clipboardMessage?>">
</div>