<div class="container">
	<div style="margin-top: 10px;">
    	<div class="col-lg-3 col-md-3 col-xs-12">
    		<div class="list-group" id="calls">
            </div>
    	</div>
    	<div class="col-lg-9 col-md-9">
        	<div class="row">
            	<div class="col-lg-8 col-md-8 col-xs-12">
            		<div id="messages">
            		</div>
            	</div>
            	<div class="col-lg-4 col-md-4 col-xs-12">
            		<div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Painel de Atendimento</h3>
                      </div>
                      <div class="panel-body">
                      	<p><a href="javascript:void(0)">Iniciar atendimento</a></p>
                      	<p><a href="javascript:void(0)">Enviar número do protocolo</a></p>
                      	<p><a href="javascript:void(0)">Adicionar Observação</a></p>
                      	<form id="post-obs">
                      		<textarea class="form-control"></textarea>
                      		<button class="btn btn-xs btn-primary pull-right">Adicionar</button>
                      	</form>
                      	<p>&nbsp;</p>
                      	<p><a href="javascript:void(0)">Adicionar Anexo</a></p>
                      	<form id="post-anexo">
                      		<input type="file" class="form-control">
                      		<button class="btn btn-xs btn-primary pull-right">Adicionar</button>
                      	</form>
                      	<p>&nbsp;</p>
                      </div>
                    </div>
            	</div>
        	</div>
    	</div>
	</div>
 </div> 

<script>

function sendMessage(form){
	var id = form.attr('id');
	$.ajax({
	    url: "<?php echo $this->url('message',array('action'=>'send-message-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:form.serialize(),
	    success: function(result){
	    	$('#'+id+' input[name="message"]').val('');
	    	showMessages($('#messages').data('call'));
	    }
	});
	
}

function getCalls(){
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'get-calls-ajax'))?>",
	    async: true,
	    type: 'POST',
	    success: function(result){
	    	$('#calls').html(result);
	    }
	});
}

getCalls();

function showMessages(idCall){
	$('#messages').data('call',idCall);
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'messages-call-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:'idCall='+idCall,
	    success: function(result){
	    	$('#messages').html(result);
	    }
	});
}

function loadAllMessages(){
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'load-messages-ajax'))?>",
	    async: true,
	    type: 'POST',
	    success: function(data){
	    	console.log(data);
	    	setTimeout("loadAllMessages();", 30000);
	    }
	});
}
loadAllMessages();


</script>
    