<div class="container">
	<div style="margin-top: 10px;">
    	<div class="col-lg-3 col-md-3 col-xs-12">
    		<div class="list-group" id="calls">
    			<div id="loading-calls" class="text-center" style="width: 35px; margin-left:100px;">
    				<img src="<?php echo $this->basePath('img/loading_apple.gif');?>" class="img-responsive">
    			</div>
            </div>
    	</div>
    	<div class="col-lg-9 col-md-9">
        	<div class="row">
            	<div class="col-lg-8 col-md-8 col-xs-12">
            		<div id="messages" data-id="0">
            		</div>
            	</div>
            	<div class="col-lg-4 col-md-4 col-xs-12 hidden" id="panel-calls">
            		<div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Painel de Atendimento</h3>
                      </div>
                      <div class="panel-body">
                      	<p><a href="javascript:void(0)" onclick="getNmrProtocol($('.id_calls').val());">Enviar número do protocolo</a></p>
                      	<p><a href="javascript:void(0)" onclick="$('#obs-div').fadeIn('slow').removeClass('hidden'); ">Adicionar Observação</a></p>
                      	<div id="obs-div" class="hidden" style="margin-bottom: 30px;">
                          	<form id="post-obs">
                          		<textarea class="form-control" id="obs" name="obs"></textarea>
                          		<input type="hidden" name="idCall" class="id_calls">
                          		<button type="button" class="btn btn-xs btn-primary pull-right" style="margin-top: 10px;" onclick="sendObs($('#post-obs'))">Adicionar</button>
                          	</form>
                      	</div>
                      	<p><a href="javascript:void(0)" onclick="finalizeCall($('.id_calls').val())">Finalizar Pedido</a></p>
                      </div>
                    </div>
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Observações do Atendimento</h3>
                      </div>
                      <div class="panel-body">
                      	<div id="obs-list">
                      		<div style="width: 35px; margin-left:100px;">
                				<img src="<?php echo $this->basePath('img/loading_apple.gif');?>" class="img-responsive">
                			</div>
                      	</div>
                      </div>
                    </div>
            	</div>
        	</div>
    	</div>
	</div>
 </div> 

<script>

function sendMessage(form,element){
	element.attr('disabled',true);
	var id = form.attr('id');
	$.ajax({
	    url: "<?php echo $this->url('message',array('action'=>'send-message-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:form.serialize(),
	    success: function(result){
	    	$('#'+id+' input[name="message"]').val('');
	    	element.attr('disabled',false);
	     	showMessages($('.id_calls').val());
	    }
	});
}

function sendObs(form){
	$.ajax({
	    url: "<?php echo $this->url('message',array('action'=>'send-obs-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:form.serialize(),
	    success: function(result){
	    	$('#obs').val('');
	    	showMessages($('.id_calls').val());
	    	$('#obs-div').fadeOut();
	    }
	});
}

function getCalls(){
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'get-calls-ajax'))?>",
	    async: true,
	    type: 'POST',
	    success: function(result){
	    	$('#calls').html(result);
	    }
	});
}

getCalls();

function getObsCalls(idCall){
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'get-obs-call-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:'idCall='+idCall,
	    success: function(result){
	    	$('#obs-list').html(result);
	    }
	});
}

function finalizeCall(idCall){
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'finalize-call-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:'idCall='+idCall,
	    success: function(data){
		    console.log(data);
	    	getCalls();
	    	$('#messages').empty();
	    	$('#panel-calls').addClass('hidden');
	    	$('#messages').attr('data-id',0);
	    }
	});
}

function showMessages(idCall){
	$('.id_calls').val(idCall);
	$('#messages').attr('data-id',idCall);
	$('#panel-calls').removeClass('hidden');
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'messages-call-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:'idCall='+idCall,
	    success: function(result){
	    	$('#messages').html(result);
	    	getObsCalls(idCall);
	    }
	});
}

function showMessagesUnread(idCall){
	var contact = '';
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'messages-unread-call-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:'idCall='+idCall,
	    success: function(result){
	    	$('#new-messages').append(result);
	    	$('.panel-body').animate({scrollTop: 9999999}, 500);
	    	contact = $('#clipboard-new-talk').attr('data-new-talk');
	    	$('#copy-button').attr('data-clipboard-text',$('#copy-button').attr('data-clipboard-text')+" "+contact);
	    }
	});
}


function getNmrProtocol(idCall){
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'get-protocol-call-ajax'))?>",
	    async: true,
	    type: 'POST',
	    data:'idCall='+idCall,
	    success: function(data){
	    	$('input[name="message"]').val(data.result);
	    }
	});
}

/** get news Messages **/
function loadAllMessages(){
	$.ajax({
		url: "<?php echo $this->url('message',array('action'=>'load-messages-ajax'))?>",
	    async: true,
	    type: 'POST',
	    success: function(data){
	    	console.log(data);
	    	setTimeout("loadAllMessages();", 15000);
	    	getCalls();
	    	
	    	if($('#messages').attr('data-id') > 0)
    			showMessagesUnread($('#messages').attr('data-id'));
	    }
	});
}
loadAllMessages();

</script>
    