<?php if (!$user = $this->identity()) :?>
    	<div class="row">
             <div class="col-lg-4 col-md-4 col-sm-8 col-xs-12 col-lg-offset-4 col-md-offset-4">
             	<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
                  <form class="form-signin" method="post" action="<?php echo $this->url('login',array('action'=>'login')); ?>">
                    	<div class="form-group">
            				<label>Login</label>
            				<input class="form-control" type="text" name="login" maxlength="20" placeholder="Login" required="">
        				</div>
        				<div class="form-group">
            				<label>Senha</label>
            				<input class="form-control" type="password" name="password" maxlength="12" placeholder="Senha" required="">
        				</div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Logar</button>
                  </form>
              </div>
          </div>
        <style>
        li{
            list-style: none;
        }
        </style>
 <?php endif; ?>